# Generated by Django 5.1.7 on 2025-04-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applicants',
            field=models.ManyToManyField(related_name='applied_jobs', through='Job_app.Application', to='Job_app.applicant'),
        ),
    ]
