# Generated by Django 5.1.7 on 2025-04-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job_app', '0003_alter_applicant_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applied_on',
            new_name='applied_at',
        ),
    ]
