# Generated by Django 5.1.7 on 2025-04-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_app', '0004_rename_applied_on_application_applied_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(default=None, upload_to='applications/resumes/'),
            preserve_default=False,
        ),
    ]
